---
git:
  base:
    ref: origin/master
linters:
  ruby_linter:
    linter: rubocop
    base:
      - "**/*.rb"
    excludes:
      - "test/**/*"
    includes:
      - "test/test_helper.rb"
      - "test/support/**"
