---
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "bin/**/*"

Metrics/LineLength:
  Max: 100
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "test/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/NegatedIf:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes

Style/UnneededPercentQ:
  Enabled: false
