#!/usr/bin/env ruby

if File.exist?(File.expand_path("../../.git", __FILE__))
  lib = File.expand_path("../../lib", __FILE__)
  $LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
end

require "mugatu"
require "mugatu/cli"

registry = Mugatu::Registry.new
options = Mugatu::Cli::Options.new(ARGV.dup, registry)
Mugatu::Cli::Dispatcher.start(registry, options.files, options.options)
